### ISSUE TITLE
pix0-contract-common

### ISSUE THREAD

**Issue by wotori** [pix0-labs/pix0-collection-contract#1]
Could you provide pix0-contract-common?
rust_analyzer won't work with your projects out of the box.

Caused by:
  failed to read `/Users/wotori/git/sources/pix0/pix0-contract-common/Cargo.toml`

Caused by:
  No such file or directory (os error 2)

**Comment by pix0-labs** [comment]
Hi Wotori, sorry, I can't provide the entire library.  The open source of this contract is to show its validity, it's not yet meant for anyone to copy and launch their own. Thanks

**Comment by pix0-labs** [comment]
In the upcoming future, we may decide to have part of the Rust libraries to be released, if your NFTs would like to integrate with our collection or marketplace contracts

**Comment by wotori** [comment]
Ok, got it. Cool contribution to the hackathon btw!

**Comment by pix0-labs** [comment]
> 

Thanks
